-- InsecureSkipVerify turns off TLS certificate verification for an https
-- check (model.Check.InsecureSkipVerify) - the equivalent of curl -k. Exists
-- for internal/self-hosted targets whose certificate is self-signed or was
-- issued for a hostname rather than the IP the check actually dials, which
-- Go's TLS stack refuses to validate by design.
--
-- Treated as content, the same as disable_redirects/status_code_op (0010) -
-- the server doesn't consume this for alerting or graphing, only the
-- monitor's own resulting Success bit matters there - so unlike
-- interval_sec/timeout_sec/result_detail_max_chars/max_response_time_ms this
-- is wiped server-side for a private-definition check and must be supplied
-- here via -import-private-check, same as match_string already is.
ALTER TABLE checks ADD COLUMN insecure_skip_verify INTEGER NOT NULL DEFAULT 0;
